### PR TITLE
Remove dependency to aldeed:simple-schema

### LINKED ISSUE #203: Package depending on deprecated aldeed:simple-schema
Hi, 

Please see below, note from the package author: 

> Verify that aldeed:simple-schema is not listed in your .meteor/.versions file. If it is, you likely depend on some other package that has an explicit dependency on the Meteor aldeed:simple-schema package. This could cause problems or unexpected behavior. Work with that package author to get an updated version that does not explicitly depend on the aldeed:simple-schema package.

From:
https://github.com/aldeed/meteor-collection2

Can we update this package so it doesn't explicitly depend on aldeed:simple-schema?

### PR DESCRIPTION
**Pull request by abate**
- Remove aldeed:simple-schema
- Add simpl-schema as npm dependency
- Fix a couple of quirks related to the new ss api
- Remove check package as no longer needed
- Fix a minor problem with file_path -> input_path

This is a small improvement on  #204 to fix #203

### CODE REVIEW

**Comment by theosp** [comment]
Question,

[Isn't it better to take the peer-npm-deps approach](https://guide.meteor.com/writing-atmosphere-packages.html#peer-npm-dependencies)?

Thanks,
-Daniel

**Comment by haojia321** [comment]
Agree peer npm deps would be better.

**Comment by lfilho** [comment]
Great, thanks for your PR @abate . Looking forward to see it on master. @TAPevents any thoughts on this one? Cheers

**Comment by HazemKhaled** [comment]
@theosp hope to see this pull merged soon

**Comment by HazemKhaled** [comment]
@zjcompt do you think this version ready to be released?

**Comment by vparpoil** [comment]
@Zjcompt it would be great if this could be merged

**Comment by Zjcompt** [comment]
I am not a maintainer. I was just looking at the files changed and saw a review button and clicked it. I have no idea how to remove my "Approval". 

Sorry @vparpoil @HazemKhaled

**Comment by vparpoil** [comment]
ping @theosp ?

**Comment by abate** [comment]
better late than ever ! :partying_face:

**Comment by theosp** [comment]
Thanks 🙏

When I closed it, I forgot to mention it was fixed as part of v1.9.0.

**Pull request closed without merging**
