### PR TITLE
Avoid race condition in setLanguage method. Fixes #86

### LINKED ISSUE #86: setLanguage() does not work properly?
i have quite a large project with many lang files.

when I set the lang on Meteor.startup it does not switch lang. it seems like the files havent been loaded yet.

however, when i call it delayed (e.g. setTimeout(setLang, 1)) it works.

### PR DESCRIPTION
**Pull request by mpowaga**
When you call:

```javascript
TAPi18n.setLanguage('pl');
TAPi18n.setLanguage('en');
```

you would expect `TAPi18n.getLanguage()` to return `en`. But if `pl` takes longer to load it is returned instead.

This fix makes sure last call always wins. However it doesn't handle situation when language can't be loaded (could be solved by letting user handle this case manually with promise object).

### CODE REVIEW

**Comment by theosp** [comment]
Thanks for this very needed PR!

Left some comments regarding the commit, please check them and LMK what you think.

Thanks,
-Daniel

**Comment by mpowaga** [comment]
Thanks @theosp! Not sure why I have created another scope for closure but I removed it and it is much cleaner now.

**Comment by theosp** [comment]
Thanks @mpowaga didn't forget this PR, had a quite busy days recently, will pull in the following days.

**Comment by theosp** [comment]
Merged.

Thanks,
-Daniel

**Pull request closed without merging**
