### PR TITLE
add YAML supports for *.i18n.yml

### PR DESCRIPTION
**Pull request by karfield**
Signed-off-by: Karfield Chen <kf2@karfield.com>

### CODE REVIEW

**Comment by theosp** [comment]
Can't pull due to too much repetition of logic that should be unified to avoid future issues (when logic will change and one file type will be forgotten), compare:

https://github.com/karfield/tap-i18n/blob/master/lib/plugin/compilers/i18n.yml.coffee
https://github.com/TAPevents/tap-i18n/blob/master/lib/plugin/compilers/i18n.json.coffee

-Daniel

**Comment by nscarcella** [comment]
@theosp @karfield how about doing something like this?

`i18n.generic.coffee`
```coffeescript
path = Npm.require "path"

helpers = share.helpers
compilers = share.compilers
compiler_configuration = share.compiler_configuration

generic_compiler = (extension, helper) -> (compileStep) ->
  compiler_configuration.registerInputFile(compileStep)
  input_path = compileStep._fullInputPath

  language = path.basename(input_path).split(".").slice(0, -2).pop()
  if _.isUndefined(language) or _.isEmpty(language)
    compileStep.error
      message: "Language-tag is not specified for *.i18n.`#{extension}' file: `#{input_path}'",
      sourcePath: input_path
    return

  if not RegExp("^#{globals.langauges_tags_regex}$").test(language)
    compileStep.error
      message: "Can't recognise '#{language}' as a language-tag: `#{input_path}'",
      sourcePath: input_path
    return

  translations = helper input_path, compileStep

  package_name = if helpers.isPackage(compileStep) then compileStep.packageName else globals.project_translations_domain
  output =
    """
    var _ = Package.underscore._,
        package_name = "#{package_name}",
        namespace = "#{package_name}";

    if (package_name != "#{globals.project_translations_domain}") {
        namespace = TAPi18n.packages[package_name].namespace;
    }

    """

  # only for project
  if not helpers.isPackage(compileStep)
    if /^(client|server)/.test(compileStep.inputPath)
      compileStep.error
        message: "Languages files should be common to the server and the client. Do not put them under /client or /server .",
        sourcePath: input_path
      return

    # add the language names to TAPi18n.languages_names 
    language_name = [language, language]
    if language_names[language]?
      language_name = language_names[language]

    if language != globals.fallback_language
      # the name for the fallback_language is part of the getProjectConfJs()'s output
      output +=
        """
        TAPi18n.languages_names["#{language}"] = #{JSON.stringify language_name};

        """

    # If this is a project but project-tap.i18n haven't compiled yet add default project conf
    # for case there is no project-tap.i18n defined in this project.
    # Reminder: we don't require projects to have project-tap.i18n
    if not(helpers.isDefaultProjectConfInserted(compileStep)) and \
       not(helpers.isProjectI18nLoaded(compileStep))
      output += share.getProjectConfJs(share.project_i18n_schema.clean {}) # defined in project-tap.i18n.coffee

      helpers.markDefaultProjectConfInserted(compileStep)


  # if fallback_language -> integrate, otherwise add to TAPi18n.translations if server arch.
  if language == compiler_configuration.fallback_language
    output +=
      """
      // integrate the fallback language translations 
      translations = {};
      translations[namespace] = #{JSON.stringify translations};
      TAPi18n._loadLangFileObject("#{compiler_configuration.fallback_language}", translations);

      """

  if compileStep.archMatches "os"
    if language != compiler_configuration.fallback_language
      output +=
        """
        if(_.isUndefined(TAPi18n.translations["#{language}"])) {
          TAPi18n.translations["#{language}"] = {};
        }

        if(_.isUndefined(TAPi18n.translations["#{language}"][namespace])) {
          TAPi18n.translations["#{language}"][namespace] = {};
        }

        _.extend(TAPi18n.translations["#{language}"][namespace], #{JSON.stringify translations});

        """

    output += 
      """
      TAPi18n._registerServerTranslator("#{language}", namespace);

      """

  # register i18n helper for templates, only once per web arch, only for packages
  if helpers.isPackage(compileStep)
    if compileStep.archMatches("web") and helpers.getCompileStepArchAndPackage(compileStep) not in compiler_configuration.templates_registered_for
      output +=
        """
        var package_templates = _.difference(_.keys(Template), non_package_templates);

        for (var i = 0; i < package_templates.length; i++) {
          var package_template = package_templates[i];

          registerI18nTemplate(package_template);
        }

        """
      compiler_configuration.templates_registered_for.push helpers.getCompileStepArchAndPackage(compileStep)

  output_path = compileStep.rootOutputPath + compileStep.inputPath.replace new RegExp("`#{extension}'$"), "js"
  compileStep.addJavaScript
    path: output_path,
    sourcePath: input_path,
    data: output,
    bare: false
```

That way you keep all repeated logic in a single place and define the concrete compilers like this:

`i18n.yml.coffee`
```coffeescript
compilers.i18n_yml = generic_compiler('yml', helpers.loadYAML)
Plugin.registerSourceHandler "i18n.yml", compilers.i18n_yml
```
`i18n.json.coffee`
```coffeescript
compilers.i18n_json = generic_compiler('json', helpers.loadJSON)
Plugin.registerSourceHandler "i18n.json", compilers.i18n_json
```

**Comment by nscarcella** [comment]
By the way, sorry if the source comment is a bit long and confusing. I can make a PR to @karfield 's fork if it is easier.

**Comment by nscarcella** [comment]
Please see my PR up there and tell me if the proposed changes would make it OK to merge this feature.

**Comment by theosp** [comment]
Merged and published as part of v1.8.0, thank you for your contribution!

**Pull request closed without merging**
