### PR TITLE
YAML support

### PR DESCRIPTION
**Pull request by nscarcella**
This is a refactor over @karfield (YAML support)[https://github.com/martinheidegger].

I'm really anxious to see this merged, so I'm trying to help by proposing some changes that may facilitate to solve the PR comments.

Didn't do much, except extracting repeated code into a generic compiler as requested by @theosp  (please see discussion in (the original PR)[https://github.com/TAPevents/tap-i18n/pull/124]).

### CODE REVIEW

**Comment by theosp** [comment]
Hi,

Thanks for taking the time to work on it.

The testing procedures we've got are a bit out-dated, meteorite based, can you give a try running them against your code?

Steps are:
* [install meteorite](https://github.com/oortcloud/meteorite#installing-meteorite)
$ cd unittest/test-packages

For automatic console test:
$ ./test-all-in-console.js

For browser based test:
$ ./test-all.bash
If you use this approach you'll have to check the result for each "Testing environment", that is, a different package.js configuration, in the browser. Once you finish testing one environment press ctrl-c to load the next one until you finish testing all of them.

Let me know how it went.

Note that the tests are weird because there's no straightforward way to test build plugins.

Thanks,
-Daniel

**Comment by theosp** [comment]
If you manage to run the tests, please add at least one test for yaml file load.

Thanks,
-Daniel

**Comment by nscarcella** [comment]
Hehe, no wonder why I wasn't able to kill the test process :P

I added a test package (which is pretty much a clone of blank-package-tap-i18n, but uses .yml files instead of .json) and everything seems to be working fine, in booth console and browser.

Let me know if something is off.

**Comment by theosp** [comment]
Thanks @nscarcella looks good.

I'll merge in the following days and publish a new version, hope to get it done Sunday.

LMK which name you want to be displayed in the credits area of the README.

-Daniel

**Comment by nscarcella** [comment]
Awesome, I'm looking forward to it!

To be fair, @karfield did the hardest part, I just polished the corners. =)

Thanks a lot for the quick response.

-Nicolás

**Comment by theosp** [comment]
Sure, I'll list the two of you

**Comment by theosp** [comment]
Merged and published as part of v1.8.0, thank you for your contribution!

**Comment by nscarcella** [comment]
Just tried it and works like a charm.

Do you think perhaps it would be worthy to add some reference to yaml support on the README.md @theosp ?

**Comment by theosp** [comment]
Sure, such a reference is very welcome.

-Daniel

**Comment by nscarcella** [comment]
Made a new PR for this (https://github.com/TAPevents/tap-i18n/pull/155)[https://github.com/TAPevents/tap-i18n/pull/155]

**Pull request closed without merging**
