### PR TITLE
Correct name for Ukrainian language

### PR DESCRIPTION
**Pull request by shkomg**
Ukrainian isn't russian or part of it - its separate language with it's own ISO code "UA"

### CODE REVIEW

**Comment by theosp** [comment]
Thanks for the PR!

**Comment by theosp** [comment]
Tell me,

Isn't it possible that there's a bit different Russian dialect in Ukraine (like en-US vs en-GB)?

I just wonder maybe it's better to keep the ru-UA.

Thanks,
-Daniel

**Comment by shkomg** [comment]
np,

no, absolutely no. I'm Ukrainian and sure about that.

Check this list for reference http://www.loc.gov/standards/iso639-2/php/code_list.php

Thank you, Daniel.

Regards,
Serhiy.

**Comment by theosp** [comment]
Alright  :)

**Pull request merged**
