### PR TITLE
meteor v1.3+ support

### PR DESCRIPTION
**Pull request by lucendio**
- now uses the new Build Plugins API (introduced in meteor v1.2)
- added meteor v1.3+ support
- complete rewrite (ES6 and modules)
- removed coffee dependency

NOTE: please see IMPORTANT.md

### CODE REVIEW

**Comment by krishaamer** [comment]
Hello TAPevents, can this please be merged? Great work @lucendio !

**Comment by lucendio** [comment]
thx, but I think it wont get merged (and imho shouldn't), until the testing (and all the tests) will work again. unfortunatly I didnt had time to address this part of the package, yet.

**Comment by benlavalley** [comment]
tap:i18n should be updated to support the new simpl-schema NPM package. https://github.com/aldeed/node-simple-schema

I cloned the current master branch to my local box and made some tweaks and it appears to work OK, allowing me to update my app to the latest simple schema / collection 2. 

@lucendio I'd be happy to share the changes I needed to make -- they mainly involved adding ecmascript as a dependency, changing the aldeed:simple-schema dependency to an NPM depenedncy in package.json, and updating two coffee files to import SimpleSchema as as well as change some schema field syntax from [String] to Array (new format for the new simple schema version).

**Comment by krishaamer** [comment]
What's the status on this?

**Comment by lucendio** [comment]
Thanks for bringing this up again. I used this trigger to write something about it [here](https://forums.meteor.com/t/the-future-of-tap-i18n-and-its-support-for-meteor-1-3/). Hopefully we will be able to figue this out.

**Comment by fadomire** [comment]
i love tap-i18n and i18next but i'm starting a new project on meteor and i'm forced to switch to alternative library because of the incompatibility. +1 for the rewrite

**Pull request closed without merging**
